/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.12 model.glb -T shadows 
Files: model.glb [21.68MB] > model-transformed.glb [3.97MB] (82%)
Author: LasquetiSpice (https://sketchfab.com/LasquetiSpice)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/animated-astronaut-character-in-space-suit-loop-8fe5c8d3365e4d87bb7bc253d53a64e1
Title: Animated Astronaut Character in Space Suit Loop
*/

import React, { useEffect, useRef } from 'react'
import { useGLTF, useAnimations } from '@react-three/drei'



export function Astronaut(props) {
  const group = useRef()
  const { nodes, materials, animations } = useGLTF('models/astronaut/model-transformed.glb')
  const { actions ,mixer} = useAnimations(animations, group);

  // Inside the component
console.log('Animations:', animations);

useEffect(() => {
  if (actions && actions['wave']) { // Use the correct animation name here
    actions['wave'].play(); // Use the correct animation name here
  }
}, [actions]);


  return (
    <group ref={group} {...props} dispose={null} castShadow>
      <group name="Sketchfab_Scene">
        <primitive object={nodes.GLTF_created_0_rootJoint} />
        <skinnedMesh name="Object_99" geometry={nodes.Object_99.geometry} material={materials.material_0} skeleton={nodes.Object_99.skeleton} scale={0.013} />
        <skinnedMesh name="Object_100" geometry={nodes.Object_100.geometry} material={materials.material_0} skeleton={nodes.Object_100.skeleton} scale={0.013} />
        <skinnedMesh name="Object_103" geometry={nodes.Object_103.geometry} material={materials.material_1} skeleton={nodes.Object_103.skeleton} scale={0.013} />
        <skinnedMesh name="Object_106" geometry={nodes.Object_106.geometry} material={materials.material_2} skeleton={nodes.Object_106.skeleton} scale={0.013} />
      </group>
    </group>
  )
}

useGLTF.preload('models/astronaut/model-transformed.glb')
